Add Zep
daytonaio/ai-enablement-stack pull request #54
Opened 2024-12-31 17:02 UTC by danielchalef

2025-01-02 10:20 UTC, ivan-burazin requested changes
Please when adding a company add it at the end of the list no the beginning, also please add it to the readme as well.

2025-01-02 15:53 UTC, ivan-burazin approved these changes

2025-01-02 15:56 UTC, danielchalef commented
@ivan-burazin Done

2025-01-02 15:57 UTC, nkkko commented
@danielchalef sorry for the trouble please do the DCO signoff

2025-01-13 18:44 UTC, nkkko commented
@danielchalef sorry was off for the last two weeks, sadly DCO fails still, see image, all commits need to be signed
![image](https://github.com/user-attachments/assets/04481040-e75b-4bc2-9887-c3e24939bd94)

2025-01-30 16:08 UTC, nkkko commented
@danielchalef hey, could you please check this, would love to add Zep

2025-01-31 05:11 UTC, danielchalef commented
Roger. On the to do list for tomorrow.

On Thu, Jan 30, 2025 at 8:09 AM, Nikola Balic < ***@***.*** > wrote:

> 
> 
> 
> 
> 
> 
> 
> @danielchalef ( https://github.com/danielchalef ) hey, could you please
> check this, would love to add Zep
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub (
> https://github.com/daytonaio/ai-enablement-stack/pull/54#issuecomment-2624923144
> ) , or unsubscribe (
> https://github.com/notifications/unsubscribe-auth/AABAAZ5NL4FGVRWTAEA3VP32NJFBZAVCNFSM6AAAAABUNWNXVGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMRUHEZDGMJUGQ
> ).
> You are receiving this because you were mentioned. Message ID: <daytonaio/ai-enablement-stack/pull/54/c2624923144
> @ github. com>
> 
> 
>

2025-02-04 03:58 UTC, danielchalef commented
@nkkko Done. Also fixed merge conflict.

2025-02-04 15:30 UTC, merged

2025-02-04 15:31 UTC, nkkko commented
Perfect, tnx!